# Generated by Django 2.2 on 2019-06-12 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_app', '0005_rate_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'permissions': (('can_vote_two_times', 'Can vote two times'),)},
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'movie')},
        ),
    ]
