# Generated by Django 2.2 on 2019-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_auto_20190612_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='alive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='alive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
