# Generated by Django 2.2 on 2019-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0008_auto_20190612_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='about',
            field=models.CharField(default='a movie', max_length=100),
        ),
    ]
