# Generated by Django 2.2 on 2019-06-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_movie_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='about',
            field=models.CharField(default='a movie', max_length=300),
        ),
    ]
