# Generated by Django 2.2 on 2019-06-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0010_auto_20190612_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
