# Generated by Django 2.2 on 2019-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0012_validatortoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
